-- Table definitions for the tournament project.
--
-- Put your SQL 'create table' statements in this file; also 'create view'
-- statements if you choose to use it.
--
-- You can write comments in this file by starting them with two dashes, like
-- these lines here.

# The 'registered_players' table holds id(player_id) and name(player_name) details of all registered players.
# The player_id field is an autogenerated serial value.
CREATE TABLE registered_players(player_id serial PRIMARY KEY, player_name varchar(50));

# The 'matches_info' table holds the information of players match records
CREATE TABLE matches_info (match_id serial PRIMARY KEY, player_id int REFERENCES registered_players(player_id), match_result int DEFAULT 0);

