-- Table definitions for the tournament project.
--
-- Put your SQL 'create table' statements in this file; also 'create view'
-- statements if you choose to use it.
--
-- You can write comments in this file by starting them with two dashes, like
-- these lines here.

"""The 'registered_players' table holds id(player_id) and name(player_name) 
details of all registered players.The player_id field is an autogenerated 
erial value.
"""

DROP DATABASE IF EXISTS tournament;
CREATE DATABASE tournament;
\c tournament;
CREATE TABLE registered_players(
player_id serial PRIMARY KEY,
player_name text,
wins int DEFAULT 0
);

"""The 'matches_info' table holds the information of players match records"""
CREATE TABLE matches_info (
match_id serial PRIMARY KEY,
player_id int REFERENCES registered_players(player_id),
match_result int DEFAULT 0
);

"""The player_match_record view stores a view of a join on the registered_players
table and the matches info table, for easy querying on finding the players win record
and the finding the swiss pairs
"""
CREATE VIEW player_match_record
AS
	SELECT p.player_id as id,p.player_name as name,COUNT(m.player_id) as matches_played,p.wins as wins
	FROM registered_players p 
		LEFT OUTER JOIN matches_info m 
		ON (p.player_id=m.player_id) 
	GROUP BY p.player_id;



